jobs:
  build-container:
    working_directory: ~/circleci-js-data-structures
    docker:
      - image: "circleci/node:14.15.2"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  run-tests:
    working_directory: ~/circleci-js-data-structures
    docker:
      - image: "circleci/node:14.15.2"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: linting
          command: npm run lint
      - run:
          name: tests
          command: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  run-tests:
    jobs:
      - build-container
      - run-tests:
          requires:
            - build-container
